### ISSUE TITLE
Setting `ENVIRONEMNT_NAME=PROD` still uses sandbox environment

### ISSUE THREAD

**Issue by dylanhand** [SSLcom/ci-images#4]
Setting the environment variable `ENVIRONMENT_NAME=PROD` in a `.env` file still uses the sandbox environment.

The only way I was able to use production was by omitting the `ENVIRONMENT_NAME` from the `.env` file entirely.

--- 

Steps to reproduce:
1. Create a `.env` with the following contents:
```bash
# .env
USERNAME=your_sandbox_username
PASSWORD=your_sandbox_password
ENVIROMENT_NAME=TEST
```
2. run `docker run -it --rm --env-file .env ghcr.io/sslcom/codesigner:latest get_credential_ids`

**Result:** ✅ sandbox certificate IDs are printed as expected 

3. Now, change to the production server by changing the below line in `.env`:
```bash
# .env
USERNAME=your_sandbox_username
PASSWORD=your_sandbox_password
ENVIRONMENT_NAME=PROD # Use PROD instead of TEST
```

4. Again run `docker run -it --rm --env-file .env ghcr.io/sslcom/codesigner:latest get_credential_ids`

**Expected result:** this should fail (assuming sandbox/prod account username/password differ)

**Result:** ❌ sandbox certificate IDs are still printed, indicating that changing `ENVIRONMENT_NAME` had no effect.

5. Now remove the `ENVIRONMENT_NAME` variable from `.env` entirely so it looks like:
```bash
# .env
USERNAME=your_sandbox_username
PASSWORD=your_sandbox_password
```

6. Again run `docker run -it --rm --env-file .env ghcr.io/sslcom/codesigner:latest get_credential_ids`

**Result:** ✅ failure to authenticate as expected since the default environment is PROD and sandbox credentials are listed in `.env`

---

I made a screen recording as well. Let me know if it's needed and I can edit out sensitive info and post it.

**Comment by bayrakmustafa** [comment]
@dylanhand There was a problem with the comment line in the env file. The problem occurs when we add a comment on the same line. While testing with the certificate in the PROD environment

Can you delete the '# Use PROD instead of TEST' section in the env file. The .env file content should be as follows:

```
# .env
USERNAME="your_prod_username"
PASSWORD="your_prod_password"
ENVIRONMENT_NAME=PROD
```

Can you update the env file like this and test it again?

**Comment by dylanhand** [comment]
@bayrakmustafa that fixed it!

Shouldn't same-line comments be allowed in the `.env` file though?

**Comment by bayrakmustafa** [comment]
@dylanhand The rules are mentioned at https://docs.docker.com/compose/environment-variables/env-file/, but there is a problem with the env variable value passed to the bash script. If it was fixed by removing the comments on the same line, it can be used this way. I'm closing the issue. Thanks for your findings.
